### ISSUE TITLE
Make character limit for both tags, and for edit tags

### ISSUE THREAD

**Issue by Ultimatnoob** [mc-labs/kaizentry#6]
Tag fields should have a limit. Both in tags, and in Edit tags, you can enter massive amounts of garbage there. It gets especially fun when you edit a tag, as seen in the following screenshot. 
![fdsakjhkjhfdajhaksdjgh fdsakaksfd](https://cloud.githubusercontent.com/assets/8882927/9952674/ac1f32be-5d95-11e5-8c36-7fb5e4c7515c.png)

**Comment by Ultimatnoob** [comment]
Also, the same thing happens when editing users.

**Comment by bobkhoda** [comment]
Fixed issue with tags and email fields
